### ISSUE TITLE
Cannot install CSVImport from Daniel-km. 

### ISSUE THREAD

**Issue by hydrosIII** [omeka-s-modules/CSVImport#113]
I do not know if this the correct place for this bug.  

I tried installing the Daniel-km version of the module. I got this module from 

https://github.com/Daniel-KM/Omeka-S-module-CSVImport/releases/download/1.1.1/CSVImport.zip

It installs, but it is not usable  since i get the following error, when trying to import a csv. 

## Steps to reproduce. 

1. Install the module, using the link above. 
2. Go to Modules > CSVImport

```
Cannot manage settings when no target ID is set.

Details:

Omeka\Service\Exception\RuntimeException: Cannot manage settings when no target ID is set. in /var/www/html/application/src/Settings/AbstractTargetSettings.php:39
Stack trace:
#0 /var/www/html/application/src/Settings/AbstractSettings.php(149): Omeka\Settings\AbstractTargetSettings->setCache()
#1 /var/www/html/application/src/Settings/AbstractSettings.php(95): Omeka\Settings\AbstractSettings->cache()
#2 /var/www/html/modules/CSVImport/src/Form/ImportForm.php(70): Omeka\Settings\AbstractSettings->get('csv_import_deli...', ',')
#3 /var/www/html/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerV3Polyfill.php(235): CSVImport\Form\ImportForm->init()
#4 /var/www/html/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(773): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Zend\ServiceManager\ServiceManager), Object(CSVImport\Form\ImportForm))
#5 /var/www/html/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('CSVImport\\Form\\...')
#6 /var/www/html/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('CSVImport\\Form\\...')
#7 /var/www/html/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php(50): Zend\ServiceManager\AbstractPluginManager->get('CSVImport\\Form\\...', NULL, true)
#8 /var/www/html/application/src/Mvc/Controller/Plugin/GetForm.php(18): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('CSVImport\\Form\\...', NULL)
#9 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke('CSVImport\\Form\\...')
#10 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(276): call_user_func_array(Object(Omeka\Mvc\Controller\Plugin\GetForm), Array)
#11 /var/www/html/modules/CSVImport/src/Controller/IndexController.php(53): Zend\Mvc\Controller\AbstractController->__call('getForm', Array)
#12 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): CSVImport\Controller\IndexController->indexAction()
#13 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/html/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/index.php(21): Zend\Mvc\Application->run()
#21 {main}

```

**Comment by Daniel-KM** [comment]
Thanks for trying CsvImport. 
Yes, as long as it is not yet fully merged, it's simpler to go on my fork. 
Anyway, this is a true bug. There are many options, so there may be some options that are not checked enough.
So can you give me options you used (displayed in the related job)?
