### ISSUE TITLE
CSV trows an exception and skip item import if latitude is empty

### ISSUE THREAD

**Issue by Falteri** [omeka-s-modules/CSVImport#214]
In case of import profile including latitude and longitude for mapping pinpoint setting, CSV Import trwos an error and skip the item if Latitude is empty, i.e. support Mapping only if all itmes in csv files contain coordinates.
This is the exception:

exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:654 Errors: { "o-module-mapping:lat": [ "A marker must have a numeric latitude." ], "o-module-mapping:lng": [ "A marker must have a numeric longitude." ] } Stack trace: #0 /home/simone.falteri/modules/Mapping/Module.php(499): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity() #1 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Mapping\Module->handleMarkers() #2 /var/www/html/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners() #3 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(643): Laminas\EventManager\EventManager->triggerEvent() #4 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(346): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity() #5 /var/www/html/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create() #6 /var/www/html/omeka-s/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute() #7 /home/simone.falteri/modules/CSVImport/src/Job/Import.php(348): Omeka\Api\Manager->create() #8 /home/simone.falteri/modules/CSVImport/src/Job/Import.php(255): CSVImport\Job\Import->create() #9 /home/simone.falteri/modules/CSVImport/src/Job/Import.php(194): CSVImport\Job\Import->processBatchData() #10 /var/www/html/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform() #11 /home/simone.falteri/modules/Log/src/Job/Dispatcher.php(32): Omeka\Job\DispatchStrategy\Synchronous->send() #12 /var/www/html/omeka-s/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send() #13 {main}

**Comment by zerocrates** [comment]
We're in the middle of working on some Mapping stuff right now, though not specifically this issue as of yet. I think I see the problem, but can you confirm some things for me?

- What versions of Omeka S, the CSV Import module, and the Mapping module are you using?
- What kind of import are you running? (I believe from what you posted here it's a standard "create" import for items?)
- How did you map the latitude and longitude? (I think you chose to do separate columns for each rather than one combined lat/lng column)

**Comment by zerocrates** [comment]
We don't have a release yet out, but the master branch of Mapping should resolve this issue.

**Comment by zerocrates** [comment]
The Mapping module update containing this fix, version 1.10.0, is out.
