### ISSUE TITLE
Multiple files to upload creates a failure

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#7]
Job is reported as Completed, despite exception below. Happens both doing `create` and `batchCreate`

Entirely possible that this issue is also present in all the importers.

```
2016-03-21T21:33:28+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php:428
Stack trace:
#0 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(288): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#1 /var/www/omekas/application/src/Api/Manager.php(325): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#2 /var/www/omekas/application/src/Api/Manager.php(197): Omeka\Api\Manager->executeBatchCreate(Object(Omeka\Api\Request), Object(Omeka\Api\Adapter\ItemAdapter))
#3 /var/www/omekas/application/src/Api/Manager.php(69): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#4 /var/www/omekas/modules/CSVImport/src/Job/Import.php(109): Omeka\Api\Manager->batchCreate('items', Array, Array, true)
#5 /var/www/omekas/modules/CSVImport/src/Job/Import.php(63): CSVImport\Job\Import->createItems(Array)
#6 /var/www/omekas/application/src/Job/Strategy/SynchronousStrategy.php(26): CSVImport\Job\Import->perform()
#7 /var/www/omekas/application/src/Job/Dispatcher.php(85): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#8 /var/www/omekas/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#9 {main}
```

Example offending JSON for `batchCreate`. First two import fine.

```
2016-03-21T21:33:23+00:00 DEBUG (7): Array
(
    [0] => Array
        (
            [o:item_set] => Array
                (
                )

            [0] => Array
                (
                    [0] => Array
                        (
                            [@value] => Walden
                            [property_id] => 1
                            [type] => literal
                        )

                )

            [o:media] => Array
                (
                    [0] => Array
                        (
                            [o:ingester] => url
                            [o:source] => http://upload.wikimedia.org/wikipedia/commons/2/25/Walden_Thoreau.jpg
                            [ingest_url] => http://upload.wikimedia.org/wikipedia/commons/2/25/Walden_Thoreau.jpg
                        )

                )

        )

    [1] => Array
        (
            [o:item_set] => Array
                (
                )

            [0] => Array
                (
                    [0] => Array
                        (
                            [@value] => The Count of Monte Cristo
                            [property_id] => 1
                            [type] => literal
                        )

                )

            [o:media] => Array
                (
                    [0] => Array
                        (
                            [o:ingester] => url
                            [o:source] => http://upload.wikimedia.org/wikipedia/commons/c/c3/Edmond_Dant%C3%A8s.JPG
                            [ingest_url] => http://upload.wikimedia.org/wikipedia/commons/c/c3/Edmond_Dant%C3%A8s.JPG
                        )

                )

        )

    [2] => Array
        (
            [o:item_set] => Array
                (
                )

            [0] => Array
                (
                    [0] => Array
                        (
                            [@value] => Narrative of the Life of Frederick Douglass
                            [property_id] => 1
                            [type] => literal
                        )

                )

            [o:media] => Array
                (
                    [0] => Array
                        (
                            [o:ingester] => url
                            [o:source] => http://upload.wikimedia.org/wikipedia/commons/f/f5/Sketchofdouglass.jpg
                            [ingest_url] => http://upload.wikimedia.org/wikipedia/commons/f/f5/Sketchofdouglass.jpg
                        )

                    [1] => Array
                        (
                            [o:ingester] => url
                            [o:source] =>  http://upload.wikimedia.org/wikipedia/commons/b/ba/Henry_David_Thoreau.jpg
                            [ingest_url] =>  http://upload.wikimedia.org/wikipedia/commons/b/ba/Henry_David_Thoreau.jpg
                        )

                )

        )

)
```

**Comment by patrickmj** [comment]
Also worth noting that, when the offending JSON comes first, the batchCreate doesn't recover and move on

**Comment by patrickmj** [comment]
Fixed by simply `trim()`ing the file urls, but still raising an eyebrow about the Completed status and batchCreate not moving on things described above. Thoughts on those, @zerocrates @jimsafley ?

**Comment by zerocrates** [comment]
You're setting continueOnError to true, so it just logs exceptions and keeps trying with the next item.

**Comment by patrickmj** [comment]
That makes sense of the reaching Completed status, but it doesn't look like it really does move on to the next item.

**Comment by zerocrates** [comment]
Yeah, if that's the case that there's some problem moving on, that would be the bug here, if there is one.

**Comment by patrickmj** [comment]
To reproduce:

Checkout master branch, which doesn't have the `trim` on fileUrl in `Import::buildMediaJson`

Run the import on the old, omeka 2 test file for CSVImport. Map whatever, e.g. 'title' to `dcterms:title`, and check `file` for the file Csv Header. 

First row has two files, which breaks, and it doesn't move along. 

Move or remove the double-file in the CSV file. Import again.

My results are that as soon as it hits the double-file, the import stops and does not move on to the next row.
